compositionIdentifier: company.internal
provider:
  baseURL: https://raw.githubusercontent.com/haarchri/%s/%s/package/crds/%s
  name: xrds-public-private
  version: main
labels:
  fromCRD:
  - example-company/psp-element
tags:
  fromLabels:
  - example-company/psp-element
